const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const app=require('../server'),db=require('../database/db');
(async()=>{const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;const results={started:new Date().toISOString(),environment:'Local Windows / isolated sql.js database',checks:[]};let token;
async function api(route,method='GET',body,bearer=token){const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...(bearer?{Authorization:'Bearer '+bearer}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {http:r.status,data:await r.json()};}
const pass=(name)=>{results.checks.push(name);console.log('PASS',name);};
try{
const login=await api('/auth/login','POST',{username:process.env.TEST_ADMIN_USERNAME,password:process.env.TEST_ADMIN_PASSWORD});assert.equal(login.http,200);token=login.data.token;
const count=30;const created=await Promise.all(Array.from({length:count},(_,i)=>api('/news','POST',{title:'并发验收-'+i,category:'research',content:'<p>并发发布</p>',publish_date:'2026-09-27',is_active:1})));
assert(created.every(r=>r.http===201));assert.equal(new Set(created.map(r=>r.data.id)).size,count);assert.equal((await db.get("SELECT COUNT(*) AS n FROM news WHERE title LIKE '并发验收-%'")).n,count);pass('30 simultaneous publications: unique IDs, no lost records');
const id=created[0].data.id;let current=(await api('/news')).data.news.find(n=>n.id===id);
const updates=await Promise.all(Array.from({length:12},(_,i)=>api('/news/'+id,'PUT',{...current,title:'并发修改-'+i})));
assert.equal(updates.filter(r=>r.http===200).length,1);assert.equal(updates.filter(r=>r.http===409).length,11);const winner=updates.findIndex(r=>r.http===200);assert.equal((await db.get('SELECT title FROM news WHERE id=?',[id])).title,'并发修改-'+winner);pass('12 concurrent edits: one winner, eleven conflicts, no silent overwrite');
const stale=await api('/news/'+id,'PUT',{...current,title:'过期覆盖'});assert.equal(stale.http,409);pass('stale browser edit is rejected');
const reg=await api('/auth/register','POST',{username:'reliability_user',name:'并发验收成员',email:'stress@example.org',password:'Reliability2026'});assert.equal(reg.http,201);const user=(await api('/accounts')).data.users.find(u=>u.username==='reliability_user');assert.equal((await api('/accounts/'+user.id,'PUT',{status:'active'})).http,200);const userToken=(await api('/auth/login','POST',{username:user.username,password:'Reliability2026'})).data.token;
const submission=(await api('/contributions','POST',{type:'news',status:'pending',payload:{title:'并发审核新闻',category:'research'}},userToken)).data;
const decisions=await Promise.all(Array.from({length:10},()=>api('/reviews/'+submission.id+'/decision','POST',{decision:'approve',version:1})));
assert.equal(decisions.filter(r=>r.http===200).length,1);assert.equal(decisions.filter(r=>r.http===409).length,9);assert.equal((await db.get("SELECT COUNT(*) AS n FROM news WHERE title='并发审核新闻'")).n,1);pass('10 simultaneous approvals: exactly one publication');
const approved=(await api('/contributions','GET',undefined,userToken)).data.owned.find(x=>x.type==='news');
const edits=await Promise.all(Array.from({length:8},()=>api('/contributions','POST',{type:'news',target_id:approved.record.id,status:'pending',payload:{title:'修改申请',category:'research'}},userToken)));assert.equal(edits.filter(r=>r.http===201).length,1);assert.equal(edits.filter(r=>r.http===409).length,7);pass('8 simultaneous change submissions: no duplicate pending revisions');
for(const payload of [{title:'格式错误',category:'research',content:{}},{title:'格式错误',category:'research',summary:[]},{title:'x'.repeat(201),category:'research'}])assert.equal((await api('/news','POST',payload)).http,400);
let response=await fetch(base+'/api/news',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:'{bad'});assert.equal(response.status,400);assert((await response.json()).message);
response=await fetch(base+'/api/news',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({content:'x'.repeat(1100000)})});assert.equal(response.status,413);assert((await response.json()).message);pass('invalid JSON, invalid field types and oversize requests return usable errors');
assert.equal((await api('/contributions','POST',{type:'__proto__',payload:{},status:'pending'},userToken)).http,400);
for(const suffix of ['-1','0','abc','999999999'])assert.notEqual((await api('/accounts/'+suffix,'PUT',{status:'active'})).http,200);pass('unknown content types and invalid IDs rejected');
const setting=await api('/settings');
const settingsSaves=await Promise.all([api('/settings','PUT',{site_description:'first',_revision:setting.data._revision}),api('/settings','PUT',{site_description:'second',_revision:setting.data._revision})]);assert.equal(settingsSaves.filter(x=>x.http===200).length,1);assert.equal(settingsSaves.filter(x=>x.http===409).length,1);
const doc=await api('/page-content/about-intro');const pages=await Promise.all([api('/page-content/about-intro','PUT',{content:'<p>version 1</p>',_revision:doc.data._revision}),api('/page-content/about-intro','PUT',{content:'<p>version 2</p>',_revision:doc.data._revision})]);assert.equal(pages.filter(x=>x.http===200).length,1);assert.equal(pages.filter(x=>x.http===409).length,1);pass('settings and page-content concurrent edits protected');
const files=fs.readdirSync(process.env.LAB_UPLOAD_DIR);
for(const [name,blob,expected]of [['fake.png',new Blob(['<script>bad()</script>'],{type:'image/png'}),400],['large.pdf',new Blob(['%PDF-'+ 'x'.repeat(10*1024*1024)],{type:'application/pdf'}),400],['blocked.html',new Blob(['bad'],{type:'text/html'}),400]]){const body=new FormData();body.append('file',blob,name);const r=await fetch(base+'/api/upload',{method:'POST',headers:{Authorization:'Bearer '+token},body});assert.equal(r.status,expected,name);}
assert.deepEqual(fs.readdirSync(process.env.LAB_UPLOAD_DIR),files);pass('fake images, forbidden files and oversize uploads rejected without orphan files');
const sqlBefore=(await db.get('SELECT COUNT(*) AS n FROM news')).n;await assert.rejects(db.transaction(tx=>{tx.run("INSERT INTO news(category,title) VALUES ('research','rollback probe')");throw Error('forced rollback');}));assert.equal((await db.get('SELECT COUNT(*) AS n FROM news')).n,sqlBefore);
const locked=spawnSync(process.execPath,['-e',"require('./database/db').getDb().then(()=>process.exit(0)).catch(()=>process.exit(7))"],{env:process.env});assert.equal(locked.status,7);pass('transaction rollback and competing-process lock');
const SQL=await require('sql.js')(),disk=new SQL.Database(fs.readFileSync(process.env.LAB_DB_PATH));assert.equal(disk.exec('PRAGMA integrity_check')[0].values[0][0],'ok');assert.equal(disk.exec('SELECT COUNT(*) FROM news')[0].values[0][0],sqlBefore);disk.close();pass('on-disk integrity and persisted records match committed data');
// Bounded synthetic load: not a production capacity guarantee.
const paths=['/','/about','/team','/achievements','/news','/search?q=频谱'];const durations=[];let index=0;await Promise.all(Array.from({length:20},async()=>{while(index<120){const i=index++;const start=performance.now(),r=await fetch(base+paths[i%paths.length]);assert.equal(r.status,200);await r.text();durations.push(performance.now()-start);}}));durations.sort((a,b)=>a-b);results.load={concurrency:20,requests:120,errors:0,p50_ms:Math.round(durations[59]),p95_ms:Math.round(durations[113]),max_ms:Math.round(durations[119])};console.log('LOAD',JSON.stringify(results.load));
const cookies=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:process.env.TEST_ADMIN_USERNAME,password:process.env.TEST_ADMIN_PASSWORD})});assert(cookies.headers.get('set-cookie').includes('HttpOnly'));pass('session cookie is HttpOnly');
results.completed=new Date().toISOString();fs.mkdirSync(path.join(__dirname,'../qa-access'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../qa-access/reliability-results.json'),JSON.stringify(results,null,2));
}finally{await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
